class AddFieldsToFormK < ActiveRecord::Migration
  def change
    add_column :form_ks, :K_1A, :string
    add_column :form_ks, :K_1B, :string
    add_column :form_ks, :K_1C, :string
    add_column :form_ks, :K_1D, :string
    add_column :form_ks, :K_1E, :string
    add_column :form_ks, :K_2A, :string
    add_column :form_ks, :K_2B, :string
    add_column :form_ks, :K_2C, :string
    add_column :form_ks, :K_2D, :string
    add_column :form_ks, :K_2E, :string
    add_column :form_ks, :K_2F, :string
    add_column :form_ks, :K_2G, :string
    add_column :form_ks, :K_2H, :string
    add_column :form_ks, :K_2I, :string
    add_column :form_ks, :K_2J, :string
    add_column :form_ks, :K_2K, :string
    add_column :form_ks, :K_2L, :string
    add_column :form_ks, :K_2M, :string
    add_column :form_ks, :K_2N, :string
    add_column :form_ks, :K_2O, :string
    add_column :form_ks, :K_2P, :string
    add_column :form_ks, :K_2Q, :string
    add_column :form_ks, :K_2R, :string
    add_column :form_ks, :K_2S, :string
    add_column :form_ks, :K_2T, :string
    add_column :form_ks, :K_2U, :string
    add_column :form_ks, :K_2V, :string
    add_column :form_ks, :K_2W, :string
    add_column :form_ks, :K_2X, :string
    add_column :form_ks, :K_2Y, :string
    add_column :form_ks, :K_2Z, :string
    add_column :form_ks, :K_2AA, :string
    add_column :form_ks, :K_T, :string
    add_column :form_ks, :K_3, :string
    add_column :form_ks, :K_4, :string
    add_column :form_ks, :K_5, :string
    add_column :form_ks, :K_6, :string
    add_column :form_ks, :K_7, :string
    add_column :form_ks, :K_8, :string
    add_column :form_ks, :K_9, :string
    add_column :form_ks, :K_10, :string
    add_column :form_ks, :K_12, :string
    add_column :form_ks, :K_13, :string
    add_column :form_ks, :K_14, :string
    add_column :form_ks, :K_15A, :string
    add_column :form_ks, :K_15B, :string
    add_column :form_ks, :K_15C, :string
    add_column :form_ks, :K_15D, :string
  end
end
