class AddFieldsToFormB < ActiveRecord::Migration
  def change
    add_column :form_bs, :B_1, :string
    add_column :form_bs, :B_2, :string
    add_column :form_bs, :B_3, :string
    add_column :form_bs, :B_4, :string
    add_column :form_bs, :B_5, :string
    add_column :form_bs, :B_6, :string
    add_column :form_bs, :B_7, :string
    add_column :form_bs, :B_8, :string
    add_column :form_bs, :B_9, :string
    add_column :form_bs, :B_10, :string
    add_column :form_bs, :B_11, :string
    add_column :form_bs, :B_12, :string
    add_column :form_bs, :B_13, :string
    add_column :form_bs, :B_14, :string
    add_column :form_bs, :B_15, :string
    add_column :form_bs, :B_16, :string
    add_column :form_bs, :B_17, :string
    add_column :form_bs, :B_18, :string
    add_column :form_bs, :B_19, :string
    add_column :form_bs, :B_20, :string
    add_column :form_bs, :B_21, :string
    add_column :form_bs, :B_22, :string
    add_column :form_bs, :B_23, :string
    add_column :form_bs, :B_24, :string
    add_column :form_bs, :B_25, :string
    add_column :form_bs, :B_26, :string
    add_column :form_bs, :B_27, :string
    add_column :form_bs, :B_28, :string
    add_column :form_bs, :B_29, :string
    add_column :form_bs, :B_30, :string
    add_column :form_bs, :B_31, :string
    add_column :form_bs, :B_32, :string
    add_column :form_bs, :B_33, :string
    add_column :form_bs, :B_34, :string
    add_column :form_bs, :B_35, :string
    add_column :form_bs, :B_36, :string
    add_column :form_bs, :B_37, :string
    add_column :form_bs, :B_38, :string
    add_column :form_bs, :B_39, :string
    add_column :form_bs, :B_40, :string
    add_column :form_bs, :B_41, :string
    add_column :form_bs, :B_42, :string
    add_column :form_bs, :B_43, :string
    add_column :form_bs, :B_44, :string
    add_column :form_bs, :B_45, :string
    add_column :form_bs, :B_46, :string
    add_column :form_bs, :B_47, :string
    add_column :form_bs, :B_48, :string
    add_column :form_bs, :B_49, :string
    add_column :form_bs, :B_50, :string
    add_column :form_bs, :B_51, :string
    add_column :form_bs, :B_52, :string
    add_column :form_bs, :B_53, :string
    add_column :form_bs, :B_54, :string
    add_column :form_bs, :B_55, :string
    add_column :form_bs, :B_56, :string
    add_column :form_bs, :B_57, :string
    add_column :form_bs, :B_58, :string
    add_column :form_bs, :B_59, :string
    add_column :form_bs, :B_60, :string
    add_column :form_bs, :B_61, :string
    add_column :form_bs, :B_62, :string
    add_column :form_bs, :B_total, :string
  end
end
