class AddFieldsToItem < ActiveRecord::Migration
  def change
    add_column :items, :B_1, :boolean
    add_column :items, :B_2, :boolean
    add_column :items, :B_3, :boolean
    add_column :items, :B_4, :boolean
    add_column :items, :B_5, :boolean
    add_column :items, :B_6, :boolean
    add_column :items, :B_7, :boolean
    add_column :items, :B_8, :boolean
    add_column :items, :B_9, :boolean
    add_column :items, :B_10, :boolean
    add_column :items, :B_11, :boolean
    add_column :items, :B_12, :boolean
    add_column :items, :B_13, :boolean
    add_column :items, :B_14, :boolean
    add_column :items, :B_15, :boolean
    add_column :items, :B_16, :boolean
    add_column :items, :B_17, :boolean
    add_column :items, :B_18, :boolean
    add_column :items, :B_19, :boolean
    add_column :items, :B_20, :boolean
    add_column :items, :B_21, :boolean
    add_column :items, :B_22, :boolean
    add_column :items, :B_23, :boolean
    add_column :items, :B_24, :boolean
    add_column :items, :B_25, :boolean
    add_column :items, :B_26, :boolean
    add_column :items, :B_27, :boolean
    add_column :items, :B_28, :boolean
    add_column :items, :B_29, :boolean
    add_column :items, :B_30, :boolean
    add_column :items, :B_31, :boolean
    add_column :items, :B_32, :boolean
    add_column :items, :B_33, :boolean
    add_column :items, :B_34, :boolean
    add_column :items, :B_35, :boolean
    add_column :items, :B_36, :boolean
    add_column :items, :B_37, :boolean
    add_column :items, :B_38, :boolean
    add_column :items, :B_39, :boolean
    add_column :items, :B_40, :boolean
    add_column :items, :B_41, :boolean
    add_column :items, :B_42, :boolean
    add_column :items, :B_43, :boolean
    add_column :items, :B_44, :boolean
    add_column :items, :B_45, :boolean
    add_column :items, :B_46, :boolean
    add_column :items, :B_47, :boolean
    add_column :items, :B_48, :boolean
    add_column :items, :B_49, :boolean
    add_column :items, :B_50, :boolean
    add_column :items, :B_51, :boolean
    add_column :items, :B_52, :boolean
    add_column :items, :B_53, :boolean
    add_column :items, :B_54, :boolean
    add_column :items, :B_55, :boolean
    add_column :items, :B_56, :boolean
    add_column :items, :B_57, :boolean
    add_column :items, :B_58, :boolean
    add_column :items, :B_59, :boolean
    add_column :items, :B_60, :boolean
    add_column :items, :B_61, :boolean
    add_column :items, :B_62, :boolean
    add_column :items, :B_total, :boolean
    add_column :items, :K_1A, :boolean
    add_column :items, :K_1B, :boolean
    add_column :items, :K_1C, :boolean
    add_column :items, :K_1D, :boolean
    add_column :items, :K_1E, :boolean
    add_column :items, :K_2A, :boolean
    add_column :items, :K_2B, :boolean
    add_column :items, :K_2C, :boolean
    add_column :items, :K_2D, :boolean
    add_column :items, :K_2E, :boolean
    add_column :items, :K_2F, :boolean
    add_column :items, :K_2G, :boolean
    add_column :items, :K_2H, :boolean
    add_column :items, :K_2I, :boolean
    add_column :items, :K_2J, :boolean
    add_column :items, :K_2K, :boolean
    add_column :items, :K_2L, :boolean
    add_column :items, :K_2M, :boolean
    add_column :items, :K_2N, :boolean
    add_column :items, :K_2O, :boolean
    add_column :items, :K_2P, :boolean
    add_column :items, :K_2Q, :boolean
    add_column :items, :K_2R, :boolean
    add_column :items, :K_2S, :boolean
    add_column :items, :K_2T, :boolean
    add_column :items, :K_2U, :boolean
    add_column :items, :K_2V, :boolean
    add_column :items, :K_2W, :boolean
    add_column :items, :K_2X, :boolean
    add_column :items, :K_2Y, :boolean
    add_column :items, :K_2Z, :boolean
    add_column :items, :K_2AA, :boolean
    add_column :items, :K_T, :boolean
    add_column :items, :K_3, :boolean
    add_column :items, :K_4, :boolean
    add_column :items, :K_5, :boolean
    add_column :items, :K_6, :boolean
    add_column :items, :K_7, :boolean
    add_column :items, :K_8, :boolean
    add_column :items, :K_9, :boolean
    add_column :items, :K_10, :boolean
    add_column :items, :K_12, :boolean
    add_column :items, :K_13, :boolean
    add_column :items, :K_14, :boolean
    add_column :items, :K_15A, :boolean
    add_column :items, :K_15B, :boolean
    add_column :items, :K_15C, :boolean
    add_column :items, :K_15D, :boolean
  end
end
