class AddFieldsToFormB < ActiveRecord::Migration
  def change
    add_column :form_bs, :B_1, :boolean
    add_column :form_bs, :B_2, :boolean
    add_column :form_bs, :B_3, :boolean
    add_column :form_bs, :B_4, :boolean
    add_column :form_bs, :B_5, :boolean
    add_column :form_bs, :B_6, :boolean
    add_column :form_bs, :B_7, :boolean
    add_column :form_bs, :B_8, :boolean
    add_column :form_bs, :B_9, :boolean
    add_column :form_bs, :B_10, :boolean
    add_column :form_bs, :B_11, :boolean
    add_column :form_bs, :B_12, :boolean
    add_column :form_bs, :B_13, :boolean
    add_column :form_bs, :B_14, :boolean
    add_column :form_bs, :B_15, :boolean
    add_column :form_bs, :B_16, :boolean
    add_column :form_bs, :B_17, :boolean
    add_column :form_bs, :B_18, :boolean
    add_column :form_bs, :B_19, :boolean
    add_column :form_bs, :B_20, :boolean
    add_column :form_bs, :B_21, :boolean
    add_column :form_bs, :B_22, :boolean
    add_column :form_bs, :B_23, :boolean
    add_column :form_bs, :B_24, :boolean
    add_column :form_bs, :B_25, :boolean
    add_column :form_bs, :B_26, :boolean
    add_column :form_bs, :B_27, :boolean
    add_column :form_bs, :B_28, :boolean
    add_column :form_bs, :B_29, :boolean
    add_column :form_bs, :B_30, :boolean
    add_column :form_bs, :B_31, :boolean
    add_column :form_bs, :B_32, :boolean
    add_column :form_bs, :B_33, :boolean
    add_column :form_bs, :B_34, :boolean
    add_column :form_bs, :B_35, :boolean
    add_column :form_bs, :B_36, :boolean
    add_column :form_bs, :B_37, :boolean
    add_column :form_bs, :B_38, :boolean
    add_column :form_bs, :B_39, :boolean
    add_column :form_bs, :B_40, :boolean
    add_column :form_bs, :B_41, :boolean
    add_column :form_bs, :B_42, :boolean
    add_column :form_bs, :B_43, :boolean
    add_column :form_bs, :B_44, :boolean
    add_column :form_bs, :B_45, :boolean
    add_column :form_bs, :B_46, :boolean
    add_column :form_bs, :B_47, :boolean
    add_column :form_bs, :B_48, :boolean
    add_column :form_bs, :B_49, :boolean
    add_column :form_bs, :B_50, :boolean
    add_column :form_bs, :B_51, :boolean
    add_column :form_bs, :B_52, :boolean
    add_column :form_bs, :B_53, :boolean
    add_column :form_bs, :B_54, :boolean
    add_column :form_bs, :B_55, :boolean
    add_column :form_bs, :B_56, :boolean
    add_column :form_bs, :B_57, :boolean
    add_column :form_bs, :B_58, :boolean
    add_column :form_bs, :B_59, :boolean
    add_column :form_bs, :B_60, :boolean
    add_column :form_bs, :B_61, :boolean
    add_column :form_bs, :B_62, :boolean
    add_column :form_bs, :B_total, :boolean
  end
end
